name: Generate-snakeV3

on:
  schedule:
    - cron: '0 */1 * * *'  # Runs every 6 hours
  workflow_dispatch:       # Manual trigger

jobs:
  snake_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
            
      - name: Run Platane/snk action
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: agoniko
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
